services:
  - type: web
    name: masumi-registry-service
    env: docker
    dockerfilePath: ./registry-service/Dockerfile
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:changeme@postgres-registry:5432/postgres?schema=public
      - key: ADMIN_KEY
        value: changeme
      - key: BLOCKFROST_API_KEY_PREPROD
        value: changeme
      - key: SEED_ONLY_IF_EMPTY
        value: "TRUE"
    ports:
      - 3000

  - type: web
    name: masumi-payment-service
    env: docker
    dockerfilePath: ./payment-service/Dockerfile
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:changeme@postgres-payment:5432/postgres?schema=public
      - key: ENCRYPTION_KEY
        value: changeme
      - key: ADMIN_KEY
        value: changeme
      - key: BLOCKFROST_API_KEY_PREPROD
        value: changeme
      - key: SEED_ONLY_IF_EMPTY
        value: "TRUE"
    ports:
      - 3001

databases:
  - name: postgres-registry
    databaseName: postgres
    user: postgres
    password: changeme
    plan: free
    region: oregon

  - name: postgres-payment
    databaseName: postgres
    user: postgres
    password: changeme
    plan: free
    region: oregon
