services:
  - type: web
    name: registry-service
    env: docker
    dockerComposeFilePath: ./docker-compose.yaml
    dockerComposeService: registry-service

  - type: web
    name: payment-service
    env: docker
    dockerComposeFilePath: ./docker-compose.yaml
    dockerComposeService: payment-service
